import { GovernorateItem } from "@/types/governorate";

export const mockGovernoratesData: GovernorateItem[] = [
  // --- Egypt Governorates (27 Governorates) ---
  {
    id: "gov-cairo",
    key: "cairo",
    nameAr: "القاهرة",
    nameEn: "Cairo",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 3993,
    activeStudentsCount: 3420,
    percentage: 28.5,
    centerStudents: 2150,
    onlineStudents: 1843,
    topGradeKey: "grade3",
  },
  {
    id: "gov-giza",
    key: "giza",
    nameAr: "الجيزة",
    nameEn: "Giza",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 2995,
    activeStudentsCount: 2610,
    percentage: 21.4,
    centerStudents: 1680,
    onlineStudents: 1315,
    topGradeKey: "grade3",
  },
  {
    id: "gov-alexandria",
    key: "alexandria",
    nameAr: "الإسكندرية",
    nameEn: "Alexandria",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 2246,
    activeStudentsCount: 1980,
    percentage: 16.0,
    centerStudents: 1120,
    onlineStudents: 1126,
    topGradeKey: "grade2",
  },
  {
    id: "gov-dakahlia",
    key: "dakahlia",
    nameAr: "الدقهلية",
    nameEn: "Dakahlia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 1248,
    activeStudentsCount: 1060,
    percentage: 8.9,
    centerStudents: 620,
    onlineStudents: 628,
    topGradeKey: "grade3",
  },
  {
    id: "gov-sharqia",
    key: "sharqia",
    nameAr: "الشرقية",
    nameEn: "Sharqia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 998,
    activeStudentsCount: 850,
    percentage: 7.1,
    centerStudents: 490,
    onlineStudents: 508,
    topGradeKey: "grade1",
  },
  {
    id: "gov-gharbia",
    key: "gharbia",
    nameAr: "الغربية",
    nameEn: "Gharbia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 680,
    activeStudentsCount: 590,
    percentage: 4.8,
    centerStudents: 310,
    onlineStudents: 370,
    topGradeKey: "grade2",
  },
  {
    id: "gov-qalyubia",
    key: "qalyubia",
    nameAr: "القليوبية",
    nameEn: "Qalyubia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 540,
    activeStudentsCount: 460,
    percentage: 3.8,
    centerStudents: 280,
    onlineStudents: 260,
    topGradeKey: "grade3",
  },
  {
    id: "gov-monufia",
    key: "monufia",
    nameAr: "المنوفية",
    nameEn: "Monufia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 430,
    activeStudentsCount: 380,
    percentage: 3.1,
    centerStudents: 190,
    onlineStudents: 240,
    topGradeKey: "grade2",
  },
  {
    id: "gov-beheira",
    key: "beheira",
    nameAr: "البحيرة",
    nameEn: "Beheira",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 390,
    activeStudentsCount: 330,
    percentage: 2.8,
    centerStudents: 150,
    onlineStudents: 240,
    topGradeKey: "grade1",
  },
  {
    id: "gov-kafr-el-sheikh",
    key: "kafrElSheikh",
    nameAr: "كفر الشيخ",
    nameEn: "Kafr El Sheikh",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 320,
    activeStudentsCount: 275,
    percentage: 2.3,
    centerStudents: 110,
    onlineStudents: 210,
    topGradeKey: "grade3",
  },
  {
    id: "gov-damietta",
    key: "damietta",
    nameAr: "دمياط",
    nameEn: "Damietta",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 260,
    activeStudentsCount: 220,
    percentage: 1.8,
    centerStudents: 95,
    onlineStudents: 165,
    topGradeKey: "grade2",
  },
  {
    id: "gov-port-said",
    key: "portSaid",
    nameAr: "بورسعيد",
    nameEn: "Port Said",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 210,
    activeStudentsCount: 185,
    percentage: 1.5,
    centerStudents: 80,
    onlineStudents: 130,
    topGradeKey: "grade3",
  },
  {
    id: "gov-ismailia",
    key: "ismailia",
    nameAr: "الإسماعيلية",
    nameEn: "Ismailia",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 195,
    activeStudentsCount: 165,
    percentage: 1.4,
    centerStudents: 70,
    onlineStudents: 125,
    topGradeKey: "grade1",
  },
  {
    id: "gov-suez",
    key: "suez",
    nameAr: "السويس",
    nameEn: "Suez",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 180,
    activeStudentsCount: 155,
    percentage: 1.3,
    centerStudents: 60,
    onlineStudents: 120,
    topGradeKey: "grade2",
  },
  {
    id: "gov-faiyum",
    key: "faiyum",
    nameAr: "الفيوم",
    nameEn: "Faiyum",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 170,
    activeStudentsCount: 140,
    percentage: 1.2,
    centerStudents: 50,
    onlineStudents: 120,
    topGradeKey: "grade3",
  },
  {
    id: "gov-beni-suef",
    key: "beniSuef",
    nameAr: "بني سويف",
    nameEn: "Beni Suef",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 160,
    activeStudentsCount: 135,
    percentage: 1.1,
    centerStudents: 45,
    onlineStudents: 115,
    topGradeKey: "grade2",
  },
  {
    id: "gov-minya",
    key: "minya",
    nameAr: "المنيا",
    nameEn: "Minya",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 155,
    activeStudentsCount: 130,
    percentage: 1.1,
    centerStudents: 40,
    onlineStudents: 115,
    topGradeKey: "grade3",
  },
  {
    id: "gov-asyut",
    key: "asyut",
    nameAr: "أسيوط",
    nameEn: "Asyut",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 145,
    activeStudentsCount: 120,
    percentage: 1.0,
    centerStudents: 35,
    onlineStudents: 110,
    topGradeKey: "grade1",
  },
  {
    id: "gov-sohag",
    key: "sohag",
    nameAr: "سوهاج",
    nameEn: "Sohag",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 130,
    activeStudentsCount: 110,
    percentage: 0.9,
    centerStudents: 30,
    onlineStudents: 100,
    topGradeKey: "grade3",
  },
  {
    id: "gov-qena",
    key: "qena",
    nameAr: "قنا",
    nameEn: "Qena",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 115,
    activeStudentsCount: 95,
    percentage: 0.8,
    centerStudents: 25,
    onlineStudents: 90,
    topGradeKey: "grade2",
  },
  {
    id: "gov-luxor",
    key: "luxor",
    nameAr: "الأقصر",
    nameEn: "Luxor",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 95,
    activeStudentsCount: 80,
    percentage: 0.7,
    centerStudents: 20,
    onlineStudents: 75,
    topGradeKey: "grade3",
  },
  {
    id: "gov-aswan",
    key: "aswan",
    nameAr: "أسوان",
    nameEn: "Aswan",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 85,
    activeStudentsCount: 70,
    percentage: 0.6,
    centerStudents: 15,
    onlineStudents: 70,
    topGradeKey: "grade2",
  },
  {
    id: "gov-red-sea",
    key: "redSea",
    nameAr: "البحر الأحمر",
    nameEn: "Red Sea",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 75,
    activeStudentsCount: 60,
    percentage: 0.5,
    centerStudents: 10,
    onlineStudents: 65,
    topGradeKey: "grade3",
  },
  {
    id: "gov-matrouh",
    key: "matrouh",
    nameAr: "مطروح",
    nameEn: "Matrouh",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 60,
    activeStudentsCount: 50,
    percentage: 0.4,
    centerStudents: 10,
    onlineStudents: 50,
    topGradeKey: "grade1",
  },
  {
    id: "gov-new-valley",
    key: "newValley",
    nameAr: "الوادي الجديد",
    nameEn: "New Valley",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 45,
    activeStudentsCount: 38,
    percentage: 0.3,
    centerStudents: 5,
    onlineStudents: 40,
    topGradeKey: "grade2",
  },
  {
    id: "gov-north-sinai",
    key: "northSinai",
    nameAr: "شمال سيناء",
    nameEn: "North Sinai",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 40,
    activeStudentsCount: 32,
    percentage: 0.3,
    centerStudents: 5,
    onlineStudents: 35,
    topGradeKey: "grade3",
  },
  {
    id: "gov-south-sinai",
    key: "southSinai",
    nameAr: "جنوب سيناء",
    nameEn: "South Sinai",
    countryCode: "egypt",
    countryNameAr: "مصر",
    countryNameEn: "Egypt",
    flagEmoji: "🇪🇬",
    studentsCount: 35,
    activeStudentsCount: 28,
    percentage: 0.2,
    centerStudents: 5,
    onlineStudents: 30,
    topGradeKey: "grade2",
  },

  // --- International Regions / Countries ---
  {
    id: "reg-riyadh",
    key: "riyadh",
    nameAr: "الرياض",
    nameEn: "Riyadh",
    countryCode: "saudiArabia",
    countryNameAr: "المملكة العربية السعودية",
    countryNameEn: "Saudi Arabia",
    flagEmoji: "🇸🇦",
    studentsCount: 340,
    activeStudentsCount: 295,
    percentage: 2.4,
    centerStudents: 0,
    onlineStudents: 340,
    topGradeKey: "grade3",
  },
  {
    id: "reg-jeddah",
    key: "jeddah",
    nameAr: "جدة",
    nameEn: "Jeddah",
    countryCode: "saudiArabia",
    countryNameAr: "المملكة العربية السعودية",
    countryNameEn: "Saudi Arabia",
    flagEmoji: "🇸🇦",
    studentsCount: 280,
    activeStudentsCount: 245,
    percentage: 2.0,
    centerStudents: 0,
    onlineStudents: 280,
    topGradeKey: "grade3",
  },
  {
    id: "reg-dammam",
    key: "dammam",
    nameAr: "الدمام والمنطقة الشرقية",
    nameEn: "Dammam & Eastern Province",
    countryCode: "saudiArabia",
    countryNameAr: "المملكة العربية السعودية",
    countryNameEn: "Saudi Arabia",
    flagEmoji: "🇸🇦",
    studentsCount: 160,
    activeStudentsCount: 140,
    percentage: 1.1,
    centerStudents: 0,
    onlineStudents: 160,
    topGradeKey: "grade2",
  },
  {
    id: "reg-dubai",
    key: "dubai",
    nameAr: "دبي",
    nameEn: "Dubai",
    countryCode: "uae",
    countryNameAr: "الإمارات العربية المتحدة",
    countryNameEn: "United Arab Emirates",
    flagEmoji: "🇦🇪",
    studentsCount: 180,
    activeStudentsCount: 160,
    percentage: 1.3,
    centerStudents: 0,
    onlineStudents: 180,
    topGradeKey: "grade3",
  },
  {
    id: "reg-abu-dhabi",
    key: "abuDhabi",
    nameAr: "أبو ظبي",
    nameEn: "Abu Dhabi",
    countryCode: "uae",
    countryNameAr: "الإمارات العربية المتحدة",
    countryNameEn: "United Arab Emirates",
    flagEmoji: "🇦🇪",
    studentsCount: 140,
    activeStudentsCount: 125,
    percentage: 1.0,
    centerStudents: 0,
    onlineStudents: 140,
    topGradeKey: "grade2",
  },
  {
    id: "reg-kuwait-city",
    key: "kuwaitCity",
    nameAr: "مدينة الكويت",
    nameEn: "Kuwait City",
    countryCode: "kuwait",
    countryNameAr: "الكويت",
    countryNameEn: "Kuwait",
    flagEmoji: "🇰🇼",
    studentsCount: 160,
    activeStudentsCount: 145,
    percentage: 1.1,
    centerStudents: 0,
    onlineStudents: 160,
    topGradeKey: "grade3",
  },
  {
    id: "reg-doha",
    key: "doha",
    nameAr: "الدوحة",
    nameEn: "Doha",
    countryCode: "qatar",
    countryNameAr: "قطر",
    countryNameEn: "Qatar",
    flagEmoji: "🇶🇦",
    studentsCount: 110,
    activeStudentsCount: 95,
    percentage: 0.8,
    centerStudents: 0,
    onlineStudents: 110,
    topGradeKey: "grade3",
  },
  {
    id: "reg-amman",
    key: "amman",
    nameAr: "عمان",
    nameEn: "Amman",
    countryCode: "jordan",
    countryNameAr: "الأردن",
    countryNameEn: "Jordan",
    flagEmoji: "🇯🇴",
    studentsCount: 85,
    activeStudentsCount: 70,
    percentage: 0.6,
    centerStudents: 0,
    onlineStudents: 85,
    topGradeKey: "grade2",
  },
  {
    id: "reg-muscat",
    key: "muscat",
    nameAr: "مسقط",
    nameEn: "Muscat",
    countryCode: "oman",
    countryNameAr: "سلطنة عمان",
    countryNameEn: "Oman",
    flagEmoji: "🇴🇲",
    studentsCount: 65,
    activeStudentsCount: 55,
    percentage: 0.5,
    centerStudents: 0,
    onlineStudents: 65,
    topGradeKey: "grade1",
  },
];
